apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
data:
  mosquitto.conf: |
    listener 8883

    certfile /mosquitto/certs/server.pem
    keyfile /mosquitto/certs/server-key.pem

    require_certificate true
    use_identity_as_username true
    cafile /mosquitto/certs/root-ca.pem

    allow_anonymous false

    plugin /usr/lib/mosquitto_dynamic_security.so
    plugin_opt_config_file /mosquitto/acls/dynamic-security.json
